### ISSUE TITLE
Сделать диаграмму вариантов использования

### ISSUE THREAD

**Issue by MaxMaz111** [MaxMaz111/discordBot#7]
я не понял ну ладно

**Comment by MaxMaz111** [comment]
**Пользователь сервера:**

1. Передавать деньги другим пользователям
2. Получать ежедневную награду
3. Получать деньги за время, проведённое в голосовых каналах
4. Покупать приватные каналы
5. Покупать приватные роли

**Бот:**
1. Приветствие человека на сервере
2. Смешные ответы на ключевые слова в сообщении

**Comment by lizzzarrrd** [comment]
С приватными каналами могут быть проблемы в реализации(5 пункт)

**Comment by lizzzarrrd** [comment]
3 пункт - запись времени, проведенного человеком в войсе, за которое будут выдаваться валюта ( запись + выдача)
